# -*- coding: utf-8 -*-
"""baitapolop

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YyviAV9GoMVC5m6Eni3csD845BixyQhz
"""

#bai1
import numpy as np
import pandas as pd
a = int(input('Nhap vao a'))
b = int(input('Nhap vao b'))
print (a + b,a - b,a * b,a / b)

#bai2
a = "Hello World"
result = a[2:5]
print(result)

from os import replace
#bai3
a = "     Hello World      "
a = a.strip()

upper_a = a.upper()
lower_a = a.lower()

thay_a = a.replace('H', 'J')

print('Xoa khoang trang:',a)
print('chu hoa:', upper_a)
print('chu thuong:',lower_a)
print('Thay H bang j:',thay_a)

#bai4
a = float(input('nhap a:'))
b = float(input('nhap b:'))
if a > b:
  print("Hello World")



#bai5
a = str(input('nhap a:'))
b = str(input('nhap b:'))

if a == b:
  print("Yes")
elif a != b:
  print("No")

#bai6
a = float(input('nhap a:'))
b = float(input('nhap b:'))
if a  == b:
  print('1')
elif a > b:
  print('2')
elif a < b:
  print('3')

#Bai7
a = int(input('nhap a:'))
b = int(input('nhap b:'))
d = int(input('nhap d:'))
if a == b or d == b:
  print('Hello World')

#Bai8
a = int(input('nhap a:'))
b = int(input('nhap b:'))
c = int(input('nhap c:'))
d = int(input('nhap d:'))
if a == b or c == d:
  print('Hello World')

#Bai9
a = int(input('nhap a:'))
b = int(input('nhap b:'))
print('Yes') if a > b else print('No')

#Bai10
a = int(input('nhap a:'))
b = int(input('nhap b:'))
print("A") if a > b else print("=") if a == b else print("B")

#bai11
import numpy as np
a = int(input('nhap a:'))
for i in range(a + 1):
  print(i)
a =  np.arange( a + 1)
print (a)
a = a[a % 2 == 0]
print("b :", a)

#bai12
a = int(input("nhap a:"))
sum = 0
for i in range(a + 1):
   if i % 3 == 0 or i % 5  == 0:
    sum += i
print("Tong cac so la boi cua 3 hoac 5", sum)

#bai13
a = [1, 2, 3, 9, 78, 77]
b = [3, 4, 67, 0]
min = len(b) if len(a) > len(b) else len(a)
c = a if len(a) > len(b) else b
for i in range(min):
 c[i] = a[i] + b[i]
print(c)

import numpy as np

import random

# a. Tạo mảng ngẫu nhiên
def tao_mang(m, n):
    return [[random.randint(0, 50) for _ in range(n)] for _ in range(m)]

# In mảng
def xuat_mang(a):
    for row in a:
        print(row)

# b. Xuất dòng k
def xuat_dong(a, k):
    print(a[k])

# c. Xuất cột k
def xuat_cot(a, k):
    for row in a:
        print(row[k])

# d. Tìm dòng có tổng > 45 lớn nhất
def dong_tong_lon_nhat(a):
    max_sum = -1
    index = -1
    for i in range(len(a)):
        s = sum(a[i])
        if s > 45 and s > max_sum:
            max_sum = s
            index = i
    return index, max_sum

# e. Tìm cột có tích nhỏ nhất
def cot_tich_nho_nhat(a):
    n = len(a[0])
    min_tich = float('inf')
    index = -1
    for j in range(n):
        tich = 1
        for i in range(len(a)):
            tich *= a[i][j]
        if tich < min_tich:
            min_tich = tich
            index = j
    return index, min_tich

# f. Xuất phần tử dòng chẵn, cột lẻ
def dong_chan_cot_le(a):
    for i in range(len(a)):
        if i % 2 == 0:
            for j in range(len(a[0])):
                if j % 2 == 1:
                    print(a[i][j], end=" ")
    print()

# g. TBC phần tử chẵn thuộc dòng lẻ
def tbc_chan_dong_le(a):
    tong = dem = 0
    for i in range(len(a)):
        if i % 2 == 1:
            for x in a[i]:
                if x % 2 == 0:
                    tong += x
                    dem += 1
    return tong / dem if dem != 0 else 0

# h. TBC phần tử biên
def tbc_bien(a):
    m, n = len(a), len(a[0])
    tong = dem = 0
    for i in range(m):
        for j in range(n):
            if i == 0 or i == m-1 or j == 0 or j == n-1:
                tong += a[i][j]
                dem += 1
    return tong / dem

# i. TBC phần tử không thuộc biên
def tbc_khong_bien(a):
    m, n = len(a), len(a[0])
    tong = dem = 0
    for i in range(1, m-1):
        for j in range(1, n-1):
            tong += a[i][j]
            dem += 1
    return tong / dem if dem != 0 else 0


# Xuất
a = tao_mang(4, 5)
xuat_mang(a)

print("Dòng 1:")
xuat_dong(a, 1)

print("Cột 2:")
xuat_cot(a, 2)

print("Dòng tổng >45 lớn nhất:", dong_tong_lon_nhat(a))
print("Cột tích nhỏ nhất:", cot_tich_nho_nhat(a))

print("Dòng chẵn, cột lẻ:")
dong_chan_cot_le(a)

print("TBC chẵn dòng lẻ:", tbc_chan_dong_le(a))
print("TBC biên:", tbc_bien(a))
print("TBC không biên:", tbc_khong_bien(a))

#Bai15
class SinhVien:
    def __init__(self, ma, ten, nam_sinh, diem):
        self.ma = ma
        self.ten = ten
        self.nam_sinh = nam_sinh
        self.diem = diem

# b. Nhập danh sách
def nhap_ds(n):
    ds = []
    for _ in range(n):
        ma = input("Mã SV: ")
        ten = input("Tên: ")
        nam = int(input("Năm sinh: "))
        diem = float(input("Điểm TB: "))
        ds.append(SinhVien(ma, ten, nam, diem))
    return ds

# c. Đếm SV đủ điều kiện lên lớp (>=5)
def dem_len_lop(ds):
    return sum(1 for sv in ds if sv.diem >= 5)

# d. Xuất SV đủ 20 tuổi
def sv_20_tuoi(ds, nam_hien_tai=2025):
    for sv in ds:
        if nam_hien_tai - sv.nam_sinh == 20:
            print(sv.ten)

# e. Đếm SV hệ ĐH (ký tự 2-3 là "DH")
def dem_he_dh(ds):
    return sum(1 for sv in ds if sv.ma[2:4] == "DH")

# f. Đếm tên "Lan"
def dem_ten_lan(ds):
    return sum(1 for sv in ds if "Lan" in sv.ten)

# g. Đếm họ "Phan"
def dem_ho_phan(ds):
    return sum(1 for sv in ds if sv.ten.startswith("Phan"))


# Xuat
ds = nhap_ds(3)

print("Số SV lên lớp:", dem_len_lop(ds))
print("SV 20 tuổi:")
sv_20_tuoi(ds)

print("Số SV hệ ĐH:", dem_he_dh(ds))
print("Số SV tên Lan:", dem_ten_lan(ds))
print("Số SV họ Phan:", dem_ho_phan(ds))