# -*- coding: utf-8 -*-
"""Baitapvenha

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TD4JqWQc6_NlvvMypm565yiphaKTTxvb
"""

#Bai1
def tron_mang(a, b):
    c = []
    n = min(len(a), len(b))

    # Lấy min từng cặp
    for i in range(n):
        c.append(min(a[i], b[i]))

    # Nếu a còn phần tử
    if len(a) > n:
        c.extend(a[n:])

    # Nếu b còn phần tử
    if len(b) > n:
        c.extend(b[n:])

    return c


# Test
a = [3, 9, 1, 4]
b = [2, 7, 4, 3, 2, 8]

print(tron_mang(a, b))

#2a
def tong_tam_giac_tren_cheo_phu(a):
    n = len(a)
    tong = 0
    for i in range(n):
        for j in range(n):
            if i + j <= n - 1:  # phía trên (kể cả chéo phụ)
                tong += a[i][j]
    return tong
#2b
def doi_am_thanh_duong(a):
    for i in range(len(a)):
        for j in range(len(a[i])):
            if a[i][j] < 0:
                a[i][j] = abs(a[i][j])
    return a
#2c
def thay_so_chan(a, x):
    for i in range(len(a)):
        for j in range(len(a[i])):
            if a[i][j] % 2 == 0:
                a[i][j] = x
    return a
#2d
def toan_chan(a):
    for row in a:
        for val in row:
            if val % 2 != 0:
                return False
    return True
#2e
def doi_xung(a):
    n = len(a)
    for i in range(n):
        for j in range(n):
            if a[i][j] != a[j][i]:
                return False
    return True
#2f
def cheo_chinh_tang(a):
    n = len(a)
    for i in range(n - 1):
        if a[i][i] >= a[i + 1][i + 1]:
            return False
    return True
#2g
def xuat_tam_giac_duoi_cheo_phu(a):
    n = len(a)
    for i in range(n):
        for j in range(n):
            if i + j >= n - 1:  # phía dưới
                print(a[i][j], end=" ")
        print()
#2h
def cheo_phu_giam(a):
    n = len(a)
    for i in range(n - 1):
        if a[i][n - 1 - i] <= a[i + 1][n - 2 - i]:
            return False
    return True
#Test
a = [
    [1, -2, 3],
    [4, 5, -6],
    [7, 8, 9]
]

print("Tổng:", tong_tam_giac_tren_cheo_phu(a))
print("Đổi âm:", doi_am_thanh_duong(a))
print("Toàn chẵn:", toan_chan(a))
print("Đối xứng:", doi_xung(a))
print("Chéo chính tăng:", cheo_chinh_tang(a))
print("Chéo phụ giảm:", cheo_phu_giam(a))

print("Tam giác dưới chéo phụ:")
xuat_tam_giac_duoi_cheo_phu(a)

#Bai3
dict1 = {
    "name": "An",
    "age": 20
}

dict2 = {
    "name": "Bình",
    "age": 21
}

dict3 = {
    "name": "Cường",
    "age": 22
}

# Dictionary lớn chứa 3 dictionary con
main_dict = {
    "sv1": dict1,
    "sv2": dict2,
    "sv3": dict3
}

print(main_dict)

