# -*- coding: utf-8 -*-
"""BTVN AKT & A*

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_wTUU9u02jhzcymNFaz1ukFfLYONrOeP
"""

import heapq
import copy

# Kích thước puzzle (n > 4 vẫn dùng được)
N = 4

goal = [
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9,10,11,12],
    [13,14,15,0]
]

# Tính Manhattan Distance
def heuristic(state):
    distance = 0
    for i in range(N):
        for j in range(N):
            if state[i][j] != 0:
                value = state[i][j]
                target_x = (value - 1) // N
                target_y = (value - 1) % N
                distance += abs(i - target_x) + abs(j - target_y)
    return distance


# Tìm vị trí ô trống
def find_zero(state):
    for i in range(N):
        for j in range(N):
            if state[i][j] == 0:
                return i, j


# Sinh trạng thái kế tiếp
def get_neighbors(state):
    neighbors = []
    x, y = find_zero(state)

    moves = [
        (x-1, y),
        (x+1, y),
        (x, y-1),
        (x, y+1)
    ]

    for new_x, new_y in moves:
        if 0 <= new_x < N and 0 <= new_y < N:
            new_state = copy.deepcopy(state)
            new_state[x][y], new_state[new_x][new_y] = new_state[new_x][new_y], new_state[x][y]
            neighbors.append(new_state)

    return neighbors


# Thuật giải A*
def A_star(start):

    open_list = []
    visited = set()

    heapq.heappush(open_list, (heuristic(start), 0, start, []))

    while open_list:
        f, g, current, path = heapq.heappop(open_list)

        if current == goal:
            return path + [current]

        visited.add(str(current))

        for neighbor in get_neighbors(current):
            if str(neighbor) not in visited:
                heapq.heappush(
                    open_list,
                    (
                        g + 1 + heuristic(neighbor),
                        g + 1,
                        neighbor,
                        path + [current]
                    )
                )

    return None


# Test
start = [
    [1,2,3,4],
    [5,6,0,8],
    [9,10,7,12],
    [13,14,11,15]
]

solution = A_star(start)

if solution:
    for step in solution:
        for row in step:
            print(row)
        print("------")
else:
    print("Không tìm thấy lời giải")

import heapq

# Ma trận chi phí
graph = [
    [0, 10, 15, 20],
    [10, 0, 35, 25],
    [15, 35, 0, 30],
    [20, 25, 30, 0]
]

n = len(graph)

# heuristic (ước lượng chi phí nhỏ nhất còn lại)
def heuristic(visited):
    h = 0
    for i in range(n):
        if i not in visited:
            h += min(graph[i])
    return h


def A_star_tsp(start):

    pq = []
    heapq.heappush(pq, (0, [start], 0))

    best_cost = float('inf')
    best_path = None

    while pq:
        f, path, cost = heapq.heappop(pq)

        if len(path) == n:
            total_cost = cost + graph[path[-1]][start]

            if total_cost < best_cost:
                best_cost = total_cost
                best_path = path + [start]

            continue

        for city in range(n):
            if city not in path:
                new_cost = cost + graph[path[-1]][city]
                new_path = path + [city]

                h = heuristic(new_path)
                f = new_cost + h

                heapq.heappush(pq, (f, new_path, new_cost))

    return best_path, best_cost


path, cost = A_star_tsp(0)

print("Đường đi tối ưu:", path)
print("Chi phí:", cost)