# -*- coding: utf-8 -*-
"""Minimax và cắt tỉa alpha-beta.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/146yyAQKjja7Iwvbgy9Rva4d0d8GXA-pp
"""

import math

EMPTY = '.'
AI = 'X'
HUMAN = 'O'

class TicTacToe:
    def __init__(self, n=3, win_len=3):
        self.n = n
        self.win_len = win_len
        self.board = [[EMPTY]*n for _ in range(n)]

    def print_board(self):
        for row in self.board:
            print(" ".join(row))
        print()

    def get_moves(self):
        return [(i, j) for i in range(self.n) for j in range(self.n) if self.board[i][j] == EMPTY]

    def make_move(self, move, player):
        i, j = move
        self.board[i][j] = player

    def undo_move(self, move):
        i, j = move
        self.board[i][j] = EMPTY

    def is_full(self):
        return all(self.board[i][j] != EMPTY for i in range(self.n) for j in range(self.n))

    def check_winner(self, player):
        n, k = self.n, self.win_len

        for i in range(n):
            for j in range(n):
                if j+k <= n and all(self.board[i][j+x] == player for x in range(k)):
                    return True
                if i+k <= n and all(self.board[i+x][j] == player for x in range(k)):
                    return True
                if i+k <= n and j+k <= n and all(self.board[i+x][j+x] == player for x in range(k)):
                    return True
                if i+k <= n and j-k+1 >= 0 and all(self.board[i+x][j-x] == player for x in range(k)):
                    return True
        return False

    def evaluate(self):
        if self.check_winner(AI):
            return 10
        elif self.check_winner(HUMAN):
            return -10
        return 0


# ================= MINIMAX =================
def minimax(game, depth, is_max):
    score = game.evaluate()

    if score != 0 or game.is_full():
        return score

    if is_max:
        best = -math.inf
        for move in game.get_moves():
            game.make_move(move, AI)
            best = max(best, minimax(game, depth+1, False))
            game.undo_move(move)
        return best
    else:
        best = math.inf
        for move in game.get_moves():
            game.make_move(move, HUMAN)
            best = min(best, minimax(game, depth+1, True))
            game.undo_move(move)
        return best


# ================= ALPHA-BETA =================
def alpha_beta(game, depth, alpha, beta, is_max):
    score = game.evaluate()

    if score != 0 or game.is_full():
        return score

    if is_max:
        best = -math.inf
        for move in game.get_moves():
            game.make_move(move, AI)
            best = max(best, alpha_beta(game, depth+1, alpha, beta, False))
            game.undo_move(move)
            alpha = max(alpha, best)
            if beta <= alpha:
                break
        return best
    else:
        best = math.inf
        for move in game.get_moves():
            game.make_move(move, HUMAN)
            best = min(best, alpha_beta(game, depth+1, alpha, beta, True))
            game.undo_move(move)
            beta = min(beta, best)
            if beta <= alpha:
                break
        return best


# ================= CHỌN NƯỚC ĐI =================
def find_best_move(game, use_alpha_beta=True):
    best_val = -math.inf
    best_move = None

    for move in game.get_moves():
        game.make_move(move, AI)

        if use_alpha_beta:
            move_val = alpha_beta(game, 0, -math.inf, math.inf, False)
        else:
            move_val = minimax(game, 0, False)

        game.undo_move(move)

        if move_val > best_val:
            best_val = move_val
            best_move = move

    return best_move


# ================= GAME LOOP =================
def play_game(n=3, use_alpha_beta=True):
    game = TicTacToe(n, 3)

    print("=== TIC TAC TOE ===")
    print("Bạn là O, AI là X")
    print()

    while True:
        game.print_board()

        # Player move
        try:
            x, y = map(int, input("Nhập dòng cột (vd: 0 1): ").split())
        except:
            print("Sai định dạng!")
            continue

        if (x, y) not in game.get_moves():
            print("Ô không hợp lệ!")
            continue

        game.make_move((x, y), HUMAN)

        if game.check_winner(HUMAN):
            game.print_board()
            print("🎉 Bạn thắng!")
            break

        if game.is_full():
            game.print_board()
            print("Hòa!")
            break

        # AI move
        print("AI đang suy nghĩ...")
        move = find_best_move(game, use_alpha_beta)

        if move:
            game.make_move(move, AI)

        if game.check_winner(AI):
            game.print_board()
            print("🤖 AI thắng!")
            break

        if game.is_full():
            game.print_board()
            print("Hòa!")
            break


# ================= RUN =================
if __name__ == "__main__":
    print("1. Minimax")
    print("2. Alpha-Beta")
    choice = input("Chọn thuật toán: ")

    use_ab = True if choice == '2' else False

    size = int(input("Nhập kích thước bàn (3, 5, 10...): "))
    play_game(size, use_ab)

import chess
import math

# ================= HÀM ĐÁNH GIÁ =================
def evaluate(board):
    piece_values = {
        chess.PAWN: 1,
        chess.KNIGHT: 3,
        chess.BISHOP: 3,
        chess.ROOK: 5,
        chess.QUEEN: 9,
        chess.KING: 100
    }

    score = 0

    for piece_type in piece_values:
        score += len(board.pieces(piece_type, chess.WHITE)) * piece_values[piece_type]
        score -= len(board.pieces(piece_type, chess.BLACK)) * piece_values[piece_type]

    return score


# ================= ALPHA-BETA =================
def alpha_beta(board, depth, alpha, beta, is_max):
    if depth == 0 or board.is_game_over():
        return evaluate(board)

    if is_max:
        max_eval = -math.inf
        for move in board.legal_moves:
            board.push(move)
            eval = alpha_beta(board, depth-1, alpha, beta, False)
            board.pop()

            max_eval = max(max_eval, eval)
            alpha = max(alpha, eval)

            if beta <= alpha:
                break

        return max_eval
    else:
        min_eval = math.inf
        for move in board.legal_moves:
            board.push(move)
            eval = alpha_beta(board, depth-1, alpha, beta, True)
            board.pop()

            min_eval = min(min_eval, eval)
            beta = min(beta, eval)

            if beta <= alpha:
                break

        return min_eval


# ================= CHỌN NƯỚC ĐI =================
def find_best_move(board, depth=3):
    best_move = None
    best_value = -math.inf

    for move in board.legal_moves:
        board.push(move)
        move_value = alpha_beta(board, depth-1, -math.inf, math.inf, False)
        board.pop()

        if move_value > best_value:
            best_value = move_value
            best_move = move

    return best_move


# ================= GAME LOOP =================
def play_chess():
    board = chess.Board()

    print("=== CHESS AI ===")
    print("Bạn chơi quân trắng (nhập nước kiểu: e2e4)")
    print()

    while not board.is_game_over():
        print(board)
        print()

        # Người chơi
        move = input("Nhập nước đi: ")
        try:
            board.push_uci(move)
        except:
            print("Nước đi sai!")
            continue

        if board.is_game_over():
            break

        # AI
        print("AI đang suy nghĩ...")
        ai_move = find_best_move(board, depth=3)
        board.push(ai_move)

        print("AI đi:", ai_move)
        print()

    print(board)
    print("Game over:", board.result())


if __name__ == "__main__":
    play_chess()